# Generated by Django 5.1.1 on 2024-09-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_emb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='emb',
            field=models.BinaryField(),
        ),
    ]
